### ISSUE TITLE
Error formatting specific DOIs

### ISSUE THREAD

**Issue by mfenner** [crosscite/citeproc-doi-server#17] opened 2017-01-07 10:23 UTC
> when on http://citation.crosscite.org I entered DOI 10.1007/978-3-642-38430-1, after choosing one of elsevier-harvard styles (elsevier-harvard, elsevier-harvard-without-titles, elsevier-harvard2), the formatting returns an error: “error while formatting: Cannot read property 'length' of null”
 
> On the contrary, the same DOI produces no errors with elsevier-vancouver style. Also, other DOIs I tried with elsevier-harvard styles worked fine.
 
> Could you tell what seems to be the problem?

**Comment by richardhallett** [comment] 2018-02-09 13:46
Closing as this seems to be working correctly now. Unable to reproduce.

**Closed by richardhallett** 2018-02-09 13:46 UTC
Labels: bug, ready
